/*
 * Hangman Game in C
 * This program is a simple implementation of the Hangman game, where a player guesses numbers to match the mystery number generated by the computer. The game includes features like player name input, difficulty level selection, game continuation choice, and score tracking. Additionally, it provides functionality to display the player's score history and find the maximum and minimum scores.
 */

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

void requestName(char Name[]) {
    printf("Enter your name: ");
    scanf("%s", Name);
}

int generateMysteryNumber(int maxLimit) {
    srand(time(NULL));
    return rand() % maxLimit;
}

int getNumber() {
    int input;
    printf("Enter a number: ");
    scanf("%d", &input);
    return input;
}

void compareNumber(int inputNumber, int mysteryNumber) {
    if (inputNumber > mysteryNumber) {
        printf("It's less!\n");
    }
    else if (inputNumber < mysteryNumber) {
        printf("It's more!\n");
    }
    else {
        printf("You won!\n");
    }
}

void displayScore(int score) {
    printf("Your score: %d\n", score);
}

int chooseDifficulty() {
    int difficulty;
    int maxLimit;
    printf("\nChoose difficulty:\n1) Easy\n2) Medium\n3) Hard\n4) Very Hard\n");
    scanf("%d", &difficulty);
    switch (difficulty) {
        case 1:
            maxLimit = 10;
            break;
        case 2:
            maxLimit = 50;
            break;
        case 3:
            maxLimit = 100;
            break;
        case 4:
            maxLimit = 1000;
            break;
        default:
            printf("Difficulty not recognized.");
    }
    return maxLimit;
}

int endGame() {
    int end;
    printf("\nDo you want to continue playing?\n1) Yes\n2) No\n");
    scanf("%d", &end);
    switch (end) {
        case 1: break;
        case 2:
            return 0;
        default:
            printf("Input not recognized, the game continues\n");
    }
    return 1;
}

void displayHistory(int scoreTable[], int numGames) {
    printf("\nHere are your scores: ");
    for (int i = 0; i < numGames; i++) {
        printf("%d ", scoreTable[i]);
    }
}

int requestGame() {
    int input;
    printf("Enter the number of games you will play: ");
    scanf("%d", &input);
    return input;
}

void sortArray(int array[], int size) {
    int temp;
    for (int i = 1; i < size; i++) {
        for (int j = 0; j < i; j++) {
            if (array[j] > array[i]) {
                temp = array[i];
                array[i] = array[j];
                array[j] = temp;
            }
        }
    }
}

void displayMinMax(int array[], int size) {
    printf("\nYour highest score: %d\nYour lowest score: %d", array[size - 1], array[0]);
}
